### ISSUE TITLE
package name same as generated classes, deprecation when using latest android sdk

### ISSUE THREAD

**Issue by octavianionel-flyability** [centricular/android_rtsp_example#7]
Hello,
I have two questions here:
1) why the package of this project is org.freedesktop.gstreamer (same as the generated GStreamer)? Is there a way to modify the package in which the files get generated?
2) I saw that the generated classes contain deprecated code when using latest android sdk.
I am using "androidx.appcompat:appcompat:1.5.1", compileSdkVersion 33
and for the gstreamer, I have:
I am using gstreamer-1.0-android-universal-1.21.2
). I saw in your code that you are using sdk version 23, so in your case should be ok (no deprecation).
Any help can be appreciated, hope not to bother too much. Or is there any forum where I can post these questions?

**Comment by MathieuDuponchelle** [comment]
> why the package of this project is org.freedesktop.gstreamer (same as the generated GStreamer)? Is there a way to modify the package in which the files get generated?

No hard reason, this is just an example that you can adapt to your liking.

> I saw that the generated classes contain deprecated code when using latest android sdk.

This project was created as a one-off example four years ago. I don't do any day to day android development, so I haven't kept it updated, patches are welcome (or you can contact Centricular for paid support of course :))

**Comment by octavianionel-flyability** [comment]
> > why the package of this project is org.freedesktop.gstreamer (same as the generated GStreamer)? Is there a way to modify the package in which the files get generated?
> 
> No hard reason, this is just an example that you can adapt to your liking.
> 
> > I saw that the generated classes contain deprecated code when using latest android sdk.
> 
> This project was created as a one-off example four years ago. I don't do any day to day android development, so I haven't kept it updated, patches are welcome (or you can contact Centricular for paid support of course :))

Thank you very much for your feedback. As soon as I find the solution I will make a PR so we can merge and have it updated. Happy new year!
